name: Publish Container Image
on:
  workflow_call:
    inputs:
      organization:
        type: string
        description: The name of the organization owning the repository
        required: true
      repository:
        type: string
        description: The name of the repository to bundle
        required: true
      build_args:
        type: string
        description: The name of the repository to bundle
        required: false
      version:
        type: string
        description: The version of the jsonnet bundle
        required: true
      prefix:
        type: string
        description: The dockerhub prefix to use
        default: metio/joi
        required: false
      license:
        type: string
        description: The license of the container
        default: 0BSD
        required: false
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      security-events: write
    outputs:
      digest: ${{ steps.publish.outputs.digest }}
      image: ${{ steps.image.outputs.name }}
    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@v4
      - id: cosign-install
        name: Install Cosign
        uses: sigstore/cosign-installer@v3
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: dockerhub_login
        name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: timestamp
        name: Create Timestamp
        run: echo "date=$(date --rfc-3339=seconds)" >> $GITHUB_OUTPUT
      - id: image
        name: Image Name
        run: echo "name=docker.io/${{ inputs.prefix }}-${{ inputs.organization }}-${{ inputs.repository }}" >> $GITHUB_OUTPUT
      - id: description
        name: Description
        run: echo "text=Contains the jsonnet bundle from ${{ inputs.organization }}/${{ inputs.repository }}" >> $GITHUB_OUTPUT
      - id: publish
        name: Publish Image
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./${{ inputs.organization }}/${{ inputs.repository }}/
          file: ./${{ inputs.organization }}/${{ inputs.repository }}/Containerfile
          build-args: |
            ${{ inputs.build_args }}
          push: true
          tags: ${{ steps.image.outputs.name }}:${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=${{ inputs.organization }}-${{ inputs.repository }}
            org.opencontainers.image.description=${{ steps.description.outputs.text }}
            org.opencontainers.image.licenses=${{ inputs.license }}
            org.opencontainers.image.vendor=metio.wtf
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/${{ inputs.organization }}/${{ inputs.repository }}
            org.opencontainers.image.version=${{ inputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.timestamp.outputs.date }}
          cache-from: type=registry,ref=${{ inputs.prefix }}-${{ inputs.organization }}-${{ inputs.repository }}:buildcache
          cache-to: type=registry,ref=${{ inputs.prefix }}-${{ inputs.organization }}-${{ inputs.repository }}:buildcache,mode=max
          sbom: true
          provenance: true
      - id: sign
        name: Sign Image
        run: |
          cosign sign \
            --yes \
            --annotations "repo=${{ github.repository }}" \
            --annotations "workflow=${{ github.workflow }}" \
            --annotations "ref=${{ github.sha }}" \
            ${{ steps.image.outputs.name }}@${{ steps.publish.outputs.digest }}
      - id: documentation
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ inputs.prefix }}-${{ inputs.organization }}-${{ inputs.repository }}
          short-description: ${{ steps.description.outputs.text }}
          readme-filepath: ./${{ inputs.organization }}/${{ inputs.repository }}/README.md
